from typing import Any, Protocol

from domains.audit.domain import AuditLogRecord

from ..domain import EndpointListQuery, EndpointReference, PermissionListQuery, PermissionReference, RoleListQuery, RoleReference, UserListQuery, UserReference


class CredentialService(Protocol):
    def hash_password(self, password: str) -> str: ...

    def verify_password(self, password: str, password_hash: str) -> bool: ...

    def needs_rehash(self, password_hash: str) -> bool: ...

    def generate_openid(self, account: str, salt: str) -> str: ...

    def generate_password(self, length: int = 12) -> str: ...


class TokenIssuer(Protocol):
    def issue_token(self, user_id: int, exp_seconds: int) -> str: ...


class AuthorizationCache(Protocol):
    async def get_endpoint_permissions(self, method: str, endpoint: str) -> set[str] | None: ...

    async def set_endpoint_permissions(self, method: str, endpoint: str, permissions: set[str], ttl_seconds: int) -> None: ...

    async def get_user_permissions(self, user_id: int) -> set[str] | None: ...

    async def set_user_permissions(self, user_id: int, permissions: set[str], ttl_seconds: int) -> None: ...


class AuditLogWriter(Protocol):
    async def record(self, record: AuditLogRecord) -> Any: ...


class UserRepositoryPort(Protocol):
    async def get_by_account(self, account: str) -> Any: ...

    async def get_by_id(self, user_id: int) -> Any: ...

    async def find(self, user: UserReference) -> Any: ...

    async def exists_by_account(self, account: str) -> bool: ...

    async def list(self, query: UserListQuery) -> Any: ...

    async def create(self, account: str, password: str, open_id: str) -> Any: ...

    async def update(self, user_id: int, *, account: str | None = None, password: str | None = None) -> Any: ...

    async def list_roles(self, user: Any) -> Any: ...

    async def add_role(self, user: Any, role: Any) -> None: ...

    async def remove_role(self, user: Any, role: Any) -> None: ...

    async def has_role(self, user: Any, role: Any) -> bool: ...

    async def collect_dashboard(self, user_id: int) -> Any: ...

    async def get_permission_titles(self, user_id: int) -> set[str]: ...


class RoleRepositoryPort(Protocol):
    async def exists_by_name(self, role_name: str) -> bool: ...

    async def get_by_name(self, role_name: str) -> Any: ...

    async def find(self, role: RoleReference) -> Any: ...

    async def list(self, query: RoleListQuery) -> Any: ...

    async def create(self, role_name: str) -> Any: ...

    async def update(self, role_id: int, *, role_name: str | None = None) -> Any: ...

    async def delete(self, role: RoleReference) -> Any: ...

    async def has_permission(self, role: Any, permission: Any) -> bool: ...

    async def add_permission(self, role: Any, permission: Any) -> None: ...

    async def remove_permission(self, role: Any, permission: Any) -> None: ...


class PermissionRepositoryPort(Protocol):
    async def exists_by_title(self, permission_title: str) -> bool: ...

    async def find(self, permission: PermissionReference) -> Any: ...

    async def list(self, query: PermissionListQuery) -> Any: ...

    async def create(self, permission_title: str) -> Any: ...

    async def update(self, permission_id: int, *, permission_title: str | None = None) -> Any: ...

    async def delete(self, permission: PermissionReference) -> Any: ...


class EndpointRepositoryPort(Protocol):
    async def list_keys(self) -> set[tuple[str, str]]: ...

    async def find(self, endpoint: EndpointReference) -> Any: ...

    async def list(self, query: EndpointListQuery) -> Any: ...

    async def create(self, endpoint: str, method: str) -> Any: ...

    async def delete_by_keys(self, endpoint_keys: set[tuple[str, str]]) -> int: ...

    async def has_permission(self, endpoint: Any, permission: Any) -> bool: ...

    async def add_permission(self, endpoint: Any, permission: Any) -> None: ...

    async def remove_permission(self, endpoint: Any, permission: Any) -> None: ...

    async def get_permission_titles(self, method: str, endpoint: str) -> set[str]: ...


class RouteCatalogPort(Protocol):
    def list_routes(self) -> list[dict[str, str]]: ...
